apiVersion: apps/v1
kind: Service
metadata:
  name: app
  namespace: development
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
