---
apiVersion: apps/v1
kind: Service
metadata:
  name: app
  namespace: development
  labels:
    io.kompose.service: app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
