apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: kingsleyijomah/kubernetes:jenkins
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # this container has docker binary installed through jenkin's Dockerfile, but we want it to 
        # use the socket from the parent pod ( host )
        volumeMounts:
          - name: dockersock
            mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

# after jenkins is installed you can retrieve the password from
# kubectl logs <pod-name> -n <namespace>